name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: texicon

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.18"

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: mix setup

      - name: Compile content
        run: mix texicon.lol && mix texicon.tex

      - name: Run tests
        run: mix test
