HAI 1.3
OBTW World layout constants — compiled to Elixir + JS at build time
TLDR

I HAS A CHUNK HEIGHT ITZ 660
I HAS A WORLD WIDTH ITZ 960
I HAS A BUFFER AHEAD ITZ 2
I HAS A DEATH FALL CHUNKS ITZ 1.5
I HAS A TEMPLATE PCT ITZ 52
I HAS A GATED PCT ITZ 35
I HAS A RANDOM PCT ITZ 13

KTHXBYE
